// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budgets.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const copyBudgets = `-- name: CopyBudgets :execrows
INSERT INTO budgets (user_id, category_id, month, limit_amount)
SELECT src.user_id, src.category_id, $1::date, src.limit_amount
FROM budgets src
WHERE src.user_id = $2 AND src.month = $3::date
ON CONFLICT (user_id, category_id, month) DO NOTHING
`

type CopyBudgetsParams struct {
	ToMonth   time.Time `json:"to_month"`
	UserID    uuid.UUID `json:"user_id"`
	FromMonth time.Time `json:"from_month"`
}

// Salin anggaran dari bulan sumber ke bulan tujuan (F-06 KP3). Tidak menimpa.
func (q *Queries) CopyBudgets(ctx context.Context, arg CopyBudgetsParams) (int64, error) {
	result, err := q.db.Exec(ctx, copyBudgets, arg.ToMonth, arg.UserID, arg.FromMonth)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countBudgets = `-- name: CountBudgets :one
SELECT count(*) FROM budgets WHERE user_id = $1 AND month = $2
`

type CountBudgetsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Month  time.Time `json:"month"`
}

func (q *Queries) CountBudgets(ctx context.Context, arg CountBudgetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBudgets, arg.UserID, arg.Month)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBudget = `-- name: DeleteBudget :execrows
DELETE FROM budgets WHERE user_id = $1 AND category_id = $2 AND month = $3
`

type DeleteBudgetParams struct {
	UserID     uuid.UUID `json:"user_id"`
	CategoryID uuid.UUID `json:"category_id"`
	Month      time.Time `json:"month"`
}

func (q *Queries) DeleteBudget(ctx context.Context, arg DeleteBudgetParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBudget, arg.UserID, arg.CategoryID, arg.Month)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBudgetsWithSpent = `-- name: ListBudgetsWithSpent :many
SELECT b.category_id, b.month, b.limit_amount,
       COALESCE((
           SELECT SUM(t.amount) FROM transactions t
           WHERE t.user_id = b.user_id AND t.category_id = b.category_id
             AND t.kind = 'expense' AND t.deleted_at IS NULL
             AND t.occurred_on >= b.month AND t.occurred_on < (b.month + interval '1 month')
       ), 0)::bigint AS spent
FROM budgets b
WHERE b.user_id = $1 AND b.month = $2
ORDER BY b.created_at
`

type ListBudgetsWithSpentParams struct {
	UserID uuid.UUID `json:"user_id"`
	Month  time.Time `json:"month"`
}

type ListBudgetsWithSpentRow struct {
	CategoryID  uuid.UUID `json:"category_id"`
	Month       time.Time `json:"month"`
	LimitAmount int64     `json:"limit_amount"`
	Spent       int64     `json:"spent"`
}

// Anggaran bulan beserta pengeluaran kategori tersebut di bulan yang sama.
func (q *Queries) ListBudgetsWithSpent(ctx context.Context, arg ListBudgetsWithSpentParams) ([]ListBudgetsWithSpentRow, error) {
	rows, err := q.db.Query(ctx, listBudgetsWithSpent, arg.UserID, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBudgetsWithSpentRow{}
	for rows.Next() {
		var i ListBudgetsWithSpentRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.Month,
			&i.LimitAmount,
			&i.Spent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBudget = `-- name: UpsertBudget :exec
INSERT INTO budgets (user_id, category_id, month, limit_amount)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, category_id, month) DO UPDATE SET limit_amount = EXCLUDED.limit_amount
`

type UpsertBudgetParams struct {
	UserID      uuid.UUID `json:"user_id"`
	CategoryID  uuid.UUID `json:"category_id"`
	Month       time.Time `json:"month"`
	LimitAmount int64     `json:"limit_amount"`
}

func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) error {
	_, err := q.db.Exec(ctx, upsertBudget,
		arg.UserID,
		arg.CategoryID,
		arg.Month,
		arg.LimitAmount,
	)
	return err
}
