// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (user_id, name, kind, icon, color_token, sort_order)
VALUES ($1, $2, $3, $4, $5,
        COALESCE((SELECT max(sort_order) + 10 FROM categories WHERE user_id = $1 OR user_id IS NULL), 10))
RETURNING id, user_id, name, kind, icon, color_token, sort_order, hidden, created_at
`

type CreateCategoryParams struct {
	UserID     *uuid.UUID `json:"user_id"`
	Name       string     `json:"name"`
	Kind       string     `json:"kind"`
	Icon       string     `json:"icon"`
	ColorToken string     `json:"color_token"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.UserID,
		arg.Name,
		arg.Kind,
		arg.Icon,
		arg.ColorToken,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.Icon,
		&i.ColorToken,
		&i.SortOrder,
		&i.Hidden,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryForUser = `-- name: GetCategoryForUser :one
SELECT c.id, c.user_id, c.name, c.kind, c.icon, c.color_token,
       COALESCE(s.sort_order, c.sort_order)::int AS sort_order,
       (CASE WHEN c.user_id IS NULL THEN COALESCE(s.hidden, false) ELSE c.hidden END)::boolean AS hidden
FROM categories c
LEFT JOIN user_category_settings s ON s.category_id = c.id AND s.user_id = $1
WHERE c.id = $2 AND (c.user_id IS NULL OR c.user_id = $1)
`

type GetCategoryForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

type GetCategoryForUserRow struct {
	ID         uuid.UUID  `json:"id"`
	UserID     *uuid.UUID `json:"user_id"`
	Name       string     `json:"name"`
	Kind       string     `json:"kind"`
	Icon       string     `json:"icon"`
	ColorToken string     `json:"color_token"`
	SortOrder  int32      `json:"sort_order"`
	Hidden     bool       `json:"hidden"`
}

func (q *Queries) GetCategoryForUser(ctx context.Context, arg GetCategoryForUserParams) (GetCategoryForUserRow, error) {
	row := q.db.QueryRow(ctx, getCategoryForUser, arg.UserID, arg.ID)
	var i GetCategoryForUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.Icon,
		&i.ColorToken,
		&i.SortOrder,
		&i.Hidden,
	)
	return i, err
}

const listCategoriesForUser = `-- name: ListCategoriesForUser :many
SELECT c.id, c.user_id, c.name, c.kind, c.icon, c.color_token,
       COALESCE(s.sort_order, c.sort_order)::int AS sort_order,
       (CASE WHEN c.user_id IS NULL THEN COALESCE(s.hidden, false) ELSE c.hidden END)::boolean AS hidden
FROM categories c
LEFT JOIN user_category_settings s ON s.category_id = c.id AND s.user_id = $1
WHERE (c.user_id IS NULL OR c.user_id = $1)
ORDER BY c.kind, COALESCE(s.sort_order, c.sort_order), c.name
`

type ListCategoriesForUserRow struct {
	ID         uuid.UUID  `json:"id"`
	UserID     *uuid.UUID `json:"user_id"`
	Name       string     `json:"name"`
	Kind       string     `json:"kind"`
	Icon       string     `json:"icon"`
	ColorToken string     `json:"color_token"`
	SortOrder  int32      `json:"sort_order"`
	Hidden     bool       `json:"hidden"`
}

// Kategori bawaan + milik pengguna, dengan pengaturan per pengguna untuk bawaan.
func (q *Queries) ListCategoriesForUser(ctx context.Context, userID uuid.UUID) ([]ListCategoriesForUserRow, error) {
	rows, err := q.db.Query(ctx, listCategoriesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesForUserRow{}
	for rows.Next() {
		var i ListCategoriesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Kind,
			&i.Icon,
			&i.ColorToken,
			&i.SortOrder,
			&i.Hidden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRulesForUser = `-- name: ListRulesForUser :many
SELECT r.id, r.user_id, r.keyword, r.category_id, r.priority, c.kind
FROM category_rules r
JOIN categories c ON c.id = r.category_id
LEFT JOIN user_category_settings s ON s.category_id = c.id AND s.user_id = $1
WHERE (r.user_id IS NULL OR r.user_id = $1)
  AND (c.user_id IS NULL OR c.user_id = $1)
  AND NOT (CASE WHEN c.user_id IS NULL THEN COALESCE(s.hidden, false) ELSE c.hidden END)
`

type ListRulesForUserRow struct {
	ID         uuid.UUID  `json:"id"`
	UserID     *uuid.UUID `json:"user_id"`
	Keyword    string     `json:"keyword"`
	CategoryID uuid.UUID  `json:"category_id"`
	Priority   int32      `json:"priority"`
	Kind       string     `json:"kind"`
}

// Aturan pribadi + bawaan untuk kategori yang tidak disembunyikan pengguna.
func (q *Queries) ListRulesForUser(ctx context.Context, userID uuid.UUID) ([]ListRulesForUserRow, error) {
	rows, err := q.db.Query(ctx, listRulesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRulesForUserRow{}
	for rows.Next() {
		var i ListRulesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Keyword,
			&i.CategoryID,
			&i.Priority,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOwnCategory = `-- name: UpdateOwnCategory :one
UPDATE categories
SET name = $1, icon = $2, color_token = $3,
    sort_order = $4, hidden = $5
WHERE id = $6 AND user_id = $7
RETURNING id, user_id, name, kind, icon, color_token, sort_order, hidden, created_at
`

type UpdateOwnCategoryParams struct {
	Name       string     `json:"name"`
	Icon       string     `json:"icon"`
	ColorToken string     `json:"color_token"`
	SortOrder  int32      `json:"sort_order"`
	Hidden     bool       `json:"hidden"`
	ID         uuid.UUID  `json:"id"`
	UserID     *uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateOwnCategory(ctx context.Context, arg UpdateOwnCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateOwnCategory,
		arg.Name,
		arg.Icon,
		arg.ColorToken,
		arg.SortOrder,
		arg.Hidden,
		arg.ID,
		arg.UserID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.Icon,
		&i.ColorToken,
		&i.SortOrder,
		&i.Hidden,
		&i.CreatedAt,
	)
	return i, err
}

const upsertCategorySetting = `-- name: UpsertCategorySetting :exec
INSERT INTO user_category_settings (user_id, category_id, hidden, sort_order)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, category_id)
DO UPDATE SET hidden = EXCLUDED.hidden, sort_order = EXCLUDED.sort_order
`

type UpsertCategorySettingParams struct {
	UserID     uuid.UUID `json:"user_id"`
	CategoryID uuid.UUID `json:"category_id"`
	Hidden     bool      `json:"hidden"`
	SortOrder  *int32    `json:"sort_order"`
}

func (q *Queries) UpsertCategorySetting(ctx context.Context, arg UpsertCategorySettingParams) error {
	_, err := q.db.Exec(ctx, upsertCategorySetting,
		arg.UserID,
		arg.CategoryID,
		arg.Hidden,
		arg.SortOrder,
	)
	return err
}

const upsertUserRule = `-- name: UpsertUserRule :exec
INSERT INTO category_rules (user_id, keyword, category_id, priority)
VALUES ($1, $2, $3, 0)
ON CONFLICT (user_id, keyword) WHERE user_id IS NOT NULL
DO UPDATE SET category_id = EXCLUDED.category_id
`

type UpsertUserRuleParams struct {
	UserID     *uuid.UUID `json:"user_id"`
	Keyword    string     `json:"keyword"`
	CategoryID uuid.UUID  `json:"category_id"`
}

func (q *Queries) UpsertUserRule(ctx context.Context, arg UpsertUserRuleParams) error {
	_, err := q.db.Exec(ctx, upsertUserRule, arg.UserID, arg.Keyword, arg.CategoryID)
	return err
}
