// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: export.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const exportTransactions = `-- name: ExportTransactions :many
SELECT t.occurred_on, t.kind, t.amount, w.name AS wallet_name,
       c.name AS category_name, t.merchant, t.note, t.created_at
FROM transactions t
JOIN wallets w ON w.id = t.wallet_id
LEFT JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1 AND t.deleted_at IS NULL
  AND ($2::date IS NULL OR t.occurred_on >= $2::date)
  AND ($3::date IS NULL OR t.occurred_on < $3::date)
ORDER BY t.occurred_on, t.created_at
`

type ExportTransactionsParams struct {
	UserID     uuid.UUID  `json:"user_id"`
	MonthStart *time.Time `json:"month_start"`
	MonthEnd   *time.Time `json:"month_end"`
}

type ExportTransactionsRow struct {
	OccurredOn   time.Time `json:"occurred_on"`
	Kind         string    `json:"kind"`
	Amount       int64     `json:"amount"`
	WalletName   string    `json:"wallet_name"`
	CategoryName *string   `json:"category_name"`
	Merchant     *string   `json:"merchant"`
	Note         *string   `json:"note"`
	CreatedAt    time.Time `json:"created_at"`
}

// Semua transaksi (atau satu bulan) milik pengguna untuk ekspor CSV (F-05 KP6, F-08 KP2).
func (q *Queries) ExportTransactions(ctx context.Context, arg ExportTransactionsParams) ([]ExportTransactionsRow, error) {
	rows, err := q.db.Query(ctx, exportTransactions, arg.UserID, arg.MonthStart, arg.MonthEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportTransactionsRow{}
	for rows.Next() {
		var i ExportTransactionsRow
		if err := rows.Scan(
			&i.OccurredOn,
			&i.Kind,
			&i.Amount,
			&i.WalletName,
			&i.CategoryName,
			&i.Merchant,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
