// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Budget struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	CategoryID  uuid.UUID          `json:"category_id"`
	Month       pgtype.Date        `json:"month"`
	LimitAmount int64              `json:"limit_amount"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.NullUUID      `json:"user_id"`
	Name       string             `json:"name"`
	Kind       string             `json:"kind"`
	Icon       string             `json:"icon"`
	ColorToken string             `json:"color_token"`
	SortOrder  int32              `json:"sort_order"`
	Hidden     bool               `json:"hidden"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CategoryRule struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.NullUUID      `json:"user_id"`
	Keyword    string             `json:"keyword"`
	CategoryID uuid.UUID          `json:"category_id"`
	Priority   int32              `json:"priority"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	WalletID   uuid.UUID          `json:"wallet_id"`
	CategoryID uuid.NullUUID      `json:"category_id"`
	Kind       string             `json:"kind"`
	Amount     int64              `json:"amount"`
	OccurredOn pgtype.Date        `json:"occurred_on"`
	Merchant   pgtype.Text        `json:"merchant"`
	Note       pgtype.Text        `json:"note"`
	Source     string             `json:"source"`
	ClientID   uuid.NullUUID      `json:"client_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	GoogleSub    pgtype.Text        `json:"google_sub"`
	DisplayName  string             `json:"display_name"`
	Theme        string             `json:"theme"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Wallet struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Name           string             `json:"name"`
	Type           string             `json:"type"`
	Provider       pgtype.Text        `json:"provider"`
	InitialBalance int64              `json:"initial_balance"`
	ArchivedAt     pgtype.Timestamptz `json:"archived_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
