// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const dailySeries = `-- name: DailySeries :many
SELECT d.day::date AS day,
       COALESCE(SUM(CASE WHEN t.kind = 'income' THEN t.amount END), 0)::bigint AS income,
       COALESCE(SUM(CASE WHEN t.kind = 'expense' THEN t.amount END), 0)::bigint AS expense
FROM generate_series($1::date, $2::date, interval '1 day') AS d(day)
LEFT JOIN transactions t
       ON t.occurred_on = d.day::date AND t.user_id = $3 AND t.deleted_at IS NULL
GROUP BY d.day
ORDER BY d.day
`

type DailySeriesParams struct {
	MonthStart time.Time `json:"month_start"`
	LastDay    time.Time `json:"last_day"`
	UserID     uuid.UUID `json:"user_id"`
}

type DailySeriesRow struct {
	Day     time.Time `json:"day"`
	Income  int64     `json:"income"`
	Expense int64     `json:"expense"`
}

// Seri harian lengkap (hari tanpa transaksi = 0) untuk grafik tren.
func (q *Queries) DailySeries(ctx context.Context, arg DailySeriesParams) ([]DailySeriesRow, error) {
	rows, err := q.db.Query(ctx, dailySeries, arg.MonthStart, arg.LastDay, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailySeriesRow{}
	for rows.Next() {
		var i DailySeriesRow
		if err := rows.Scan(&i.Day, &i.Income, &i.Expense); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expenseByCategory = `-- name: ExpenseByCategory :many
SELECT t.category_id, c.name AS category_name, SUM(t.amount)::bigint AS amount
FROM transactions t
LEFT JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1 AND t.deleted_at IS NULL AND t.kind = 'expense'
  AND t.occurred_on >= $2 AND t.occurred_on < $3
GROUP BY t.category_id, c.name
ORDER BY amount DESC, c.name
`

type ExpenseByCategoryParams struct {
	UserID     uuid.UUID `json:"user_id"`
	MonthStart time.Time `json:"month_start"`
	MonthEnd   time.Time `json:"month_end"`
}

type ExpenseByCategoryRow struct {
	CategoryID   *uuid.UUID `json:"category_id"`
	CategoryName *string    `json:"category_name"`
	Amount       int64      `json:"amount"`
}

// Pengeluaran per kategori, terbesar dulu. category_id NULL = tanpa kategori.
func (q *Queries) ExpenseByCategory(ctx context.Context, arg ExpenseByCategoryParams) ([]ExpenseByCategoryRow, error) {
	rows, err := q.db.Query(ctx, expenseByCategory, arg.UserID, arg.MonthStart, arg.MonthEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseByCategoryRow{}
	for rows.Next() {
		var i ExpenseByCategoryRow
		if err := rows.Scan(&i.CategoryID, &i.CategoryName, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthTotals = `-- name: MonthTotals :one

SELECT
    COALESCE(SUM(CASE WHEN kind = 'income' THEN amount END), 0)::bigint AS income,
    COALESCE(SUM(CASE WHEN kind = 'expense' THEN amount END), 0)::bigint AS expense
FROM transactions
WHERE user_id = $1 AND deleted_at IS NULL
  AND occurred_on >= $2 AND occurred_on < $3
`

type MonthTotalsParams struct {
	UserID     uuid.UUID `json:"user_id"`
	MonthStart time.Time `json:"month_start"`
	MonthEnd   time.Time `json:"month_end"`
}

type MonthTotalsRow struct {
	Income  int64 `json:"income"`
	Expense int64 `json:"expense"`
}

// Agregat dihitung di SQL, bukan di memori aplikasi (PRD bagian 7).
func (q *Queries) MonthTotals(ctx context.Context, arg MonthTotalsParams) (MonthTotalsRow, error) {
	row := q.db.QueryRow(ctx, monthTotals, arg.UserID, arg.MonthStart, arg.MonthEnd)
	var i MonthTotalsRow
	err := row.Scan(&i.Income, &i.Expense)
	return i, err
}
