// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, last_seen_at, created_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE user_id = $1 AND expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions, userID)
	return err
}

const deleteOtherSessions = `-- name: DeleteOtherSessions :exec
DELETE FROM sessions WHERE user_id = $1 AND id <> $2
`

type DeleteOtherSessionsParams struct {
	UserID uuid.UUID `json:"user_id"`
	KeepID uuid.UUID `json:"keep_id"`
}

func (q *Queries) DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteOtherSessions, arg.UserID, arg.KeepID)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id AS session_id, s.expires_at, s.last_seen_at, u.id, u.email, u.password_hash, u.google_sub, u.display_name, u.theme, u.created_at, u.budget_auto_copy
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetSessionByTokenHashRow struct {
	SessionID      uuid.UUID `json:"session_id"`
	ExpiresAt      time.Time `json:"expires_at"`
	LastSeenAt     time.Time `json:"last_seen_at"`
	ID             uuid.UUID `json:"id"`
	Email          string    `json:"email"`
	PasswordHash   *string   `json:"password_hash"`
	GoogleSub      *string   `json:"google_sub"`
	DisplayName    string    `json:"display_name"`
	Theme          string    `json:"theme"`
	CreatedAt      time.Time `json:"created_at"`
	BudgetAutoCopy bool      `json:"budget_auto_copy"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.SessionID,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleSub,
		&i.DisplayName,
		&i.Theme,
		&i.CreatedAt,
		&i.BudgetAutoCopy,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now(), expires_at = $1 WHERE id = $2
`

type TouchSessionParams struct {
	ExpiresAt time.Time `json:"expires_at"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ExpiresAt, arg.ID)
	return err
}
