// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, wallet_id, category_id, kind, amount, occurred_on, merchant, note, client_id)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9)
ON CONFLICT (user_id, client_id) DO NOTHING
RETURNING id, user_id, wallet_id, category_id, kind, amount, occurred_on, merchant, note, source, client_id, created_at, updated_at, deleted_at
`

type CreateTransactionParams struct {
	UserID     uuid.UUID  `json:"user_id"`
	WalletID   uuid.UUID  `json:"wallet_id"`
	CategoryID *uuid.UUID `json:"category_id"`
	Kind       string     `json:"kind"`
	Amount     int64      `json:"amount"`
	OccurredOn time.Time  `json:"occurred_on"`
	Merchant   *string    `json:"merchant"`
	Note       *string    `json:"note"`
	ClientID   *uuid.UUID `json:"client_id"`
}

// Idempoten: bila client_id sudah ada untuk pengguna ini, tidak ada baris yang
// dikembalikan (pgx.ErrNoRows) dan pemanggil mengambil transaksi yang ada.
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.WalletID,
		arg.CategoryID,
		arg.Kind,
		arg.Amount,
		arg.OccurredOn,
		arg.Merchant,
		arg.Note,
		arg.ClientID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WalletID,
		&i.CategoryID,
		&i.Kind,
		&i.Amount,
		&i.OccurredOn,
		&i.Merchant,
		&i.Note,
		&i.Source,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, user_id, wallet_id, category_id, kind, amount, occurred_on, merchant, note, source, client_id, created_at, updated_at, deleted_at FROM transactions WHERE user_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetTransactionParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.UserID, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WalletID,
		&i.CategoryID,
		&i.Kind,
		&i.Amount,
		&i.OccurredOn,
		&i.Merchant,
		&i.Note,
		&i.Source,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransactionByClientID = `-- name: GetTransactionByClientID :one
SELECT id, user_id, wallet_id, category_id, kind, amount, occurred_on, merchant, note, source, client_id, created_at, updated_at, deleted_at FROM transactions WHERE user_id = $1 AND client_id = $2
`

type GetTransactionByClientIDParams struct {
	UserID   uuid.UUID  `json:"user_id"`
	ClientID *uuid.UUID `json:"client_id"`
}

func (q *Queries) GetTransactionByClientID(ctx context.Context, arg GetTransactionByClientIDParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByClientID, arg.UserID, arg.ClientID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WalletID,
		&i.CategoryID,
		&i.Kind,
		&i.Amount,
		&i.OccurredOn,
		&i.Merchant,
		&i.Note,
		&i.Source,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, user_id, wallet_id, category_id, kind, amount, occurred_on, merchant, note, source, client_id, created_at, updated_at, deleted_at FROM transactions
WHERE user_id = $1
  AND deleted_at IS NULL
  AND occurred_on >= $2 AND occurred_on < $3
  AND ($4::uuid IS NULL OR wallet_id = $4::uuid)
  AND ($5::uuid IS NULL OR category_id = $5::uuid)
  AND ($6::text IS NULL OR kind = $6::text)
  AND ($7::text IS NULL
       OR merchant ILIKE '%' || $7::text || '%' ESCAPE '\'
       OR note ILIKE '%' || $7::text || '%' ESCAPE '\')
  AND ($8::date IS NULL
       OR (occurred_on, created_at, id) < ($8::date,
                                           $9::timestamptz,
                                           $10::uuid))
ORDER BY occurred_on DESC, created_at DESC, id DESC
LIMIT $11
`

type ListTransactionsParams struct {
	UserID        uuid.UUID  `json:"user_id"`
	MonthStart    time.Time  `json:"month_start"`
	MonthEnd      time.Time  `json:"month_end"`
	WalletID      *uuid.UUID `json:"wallet_id"`
	CategoryID    *uuid.UUID `json:"category_id"`
	Kind          *string    `json:"kind"`
	Q             *string    `json:"q"`
	CursorDate    *time.Time `json:"cursor_date"`
	CursorCreated *time.Time `json:"cursor_created"`
	CursorID      *uuid.UUID `json:"cursor_id"`
	RowLimit      int32      `json:"row_limit"`
}

// Paginasi kursor (occurred_on, created_at, id) menurun. Filter opsional.
func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.UserID,
		arg.MonthStart,
		arg.MonthEnd,
		arg.WalletID,
		arg.CategoryID,
		arg.Kind,
		arg.Q,
		arg.CursorDate,
		arg.CursorCreated,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WalletID,
			&i.CategoryID,
			&i.Kind,
			&i.Amount,
			&i.OccurredOn,
			&i.Merchant,
			&i.Note,
			&i.Source,
			&i.ClientID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreTransaction = `-- name: RestoreTransaction :one
UPDATE transactions SET deleted_at = NULL, updated_at = now()
WHERE user_id = $1 AND id = $2 AND deleted_at IS NOT NULL
RETURNING id, user_id, wallet_id, category_id, kind, amount, occurred_on, merchant, note, source, client_id, created_at, updated_at, deleted_at
`

type RestoreTransactionParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) RestoreTransaction(ctx context.Context, arg RestoreTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, restoreTransaction, arg.UserID, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WalletID,
		&i.CategoryID,
		&i.Kind,
		&i.Amount,
		&i.OccurredOn,
		&i.Merchant,
		&i.Note,
		&i.Source,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :execrows
UPDATE transactions SET deleted_at = now(), updated_at = now()
WHERE user_id = $1 AND id = $2 AND deleted_at IS NULL
`

type SoftDeleteTransactionParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTransaction, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET wallet_id = $1,
    category_id = $2,
    kind = $3,
    amount = $4,
    occurred_on = $5,
    merchant = $6,
    note = $7,
    updated_at = now()
WHERE user_id = $8 AND id = $9 AND deleted_at IS NULL
RETURNING id, user_id, wallet_id, category_id, kind, amount, occurred_on, merchant, note, source, client_id, created_at, updated_at, deleted_at
`

type UpdateTransactionParams struct {
	WalletID   uuid.UUID  `json:"wallet_id"`
	CategoryID *uuid.UUID `json:"category_id"`
	Kind       string     `json:"kind"`
	Amount     int64      `json:"amount"`
	OccurredOn time.Time  `json:"occurred_on"`
	Merchant   *string    `json:"merchant"`
	Note       *string    `json:"note"`
	UserID     uuid.UUID  `json:"user_id"`
	ID         uuid.UUID  `json:"id"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.WalletID,
		arg.CategoryID,
		arg.Kind,
		arg.Amount,
		arg.OccurredOn,
		arg.Merchant,
		arg.Note,
		arg.UserID,
		arg.ID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WalletID,
		&i.CategoryID,
		&i.Kind,
		&i.Amount,
		&i.OccurredOn,
		&i.Merchant,
		&i.Note,
		&i.Source,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
