// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, google_sub, display_name)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, google_sub, display_name, theme, created_at
`

type CreateUserParams struct {
	Email        string  `json:"email"`
	PasswordHash *string `json:"password_hash"`
	GoogleSub    *string `json:"google_sub"`
	DisplayName  string  `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.GoogleSub,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleSub,
		&i.DisplayName,
		&i.Theme,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, google_sub, display_name, theme, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleSub,
		&i.DisplayName,
		&i.Theme,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByGoogleSub = `-- name: GetUserByGoogleSub :one
SELECT id, email, password_hash, google_sub, display_name, theme, created_at FROM users WHERE google_sub = $1
`

func (q *Queries) GetUserByGoogleSub(ctx context.Context, googleSub *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSub, googleSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleSub,
		&i.DisplayName,
		&i.Theme,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, google_sub, display_name, theme, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleSub,
		&i.DisplayName,
		&i.Theme,
		&i.CreatedAt,
	)
	return i, err
}

const linkGoogleAccount = `-- name: LinkGoogleAccount :one
UPDATE users SET google_sub = $1, password_hash = NULL
WHERE id = $2
RETURNING id, email, password_hash, google_sub, display_name, theme, created_at
`

type LinkGoogleAccountParams struct {
	GoogleSub *string   `json:"google_sub"`
	ID        uuid.UUID `json:"id"`
}

// Menautkan akun Google ke akun email yang sudah ada. Password dihapus karena
// email tidak pernah diverifikasi saat daftar; kepemilikan email baru terbukti
// lewat Google (mencegah pengambilalihan akun oleh pendaftar lebih dulu).
func (q *Queries) LinkGoogleAccount(ctx context.Context, arg LinkGoogleAccountParams) (User, error) {
	row := q.db.QueryRow(ctx, linkGoogleAccount, arg.GoogleSub, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleSub,
		&i.DisplayName,
		&i.Theme,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $1 WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash *string   `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = COALESCE($1, display_name),
    theme = COALESCE($2, theme)
WHERE id = $3
RETURNING id, email, password_hash, google_sub, display_name, theme, created_at
`

type UpdateUserProfileParams struct {
	DisplayName *string   `json:"display_name"`
	Theme       *string   `json:"theme"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.DisplayName, arg.Theme, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.GoogleSub,
		&i.DisplayName,
		&i.Theme,
		&i.CreatedAt,
	)
	return i, err
}
