// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallets.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (user_id, name, type, provider, initial_balance)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, type, provider, initial_balance, archived_at, created_at
`

type CreateWalletParams struct {
	UserID         uuid.UUID `json:"user_id"`
	Name           string    `json:"name"`
	Type           string    `json:"type"`
	Provider       *string   `json:"provider"`
	InitialBalance int64     `json:"initial_balance"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Provider,
		arg.InitialBalance,
	)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Provider,
		&i.InitialBalance,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWallet = `-- name: GetWallet :one
SELECT id, user_id, name, type, provider, initial_balance, archived_at, created_at FROM wallets WHERE user_id = $1 AND id = $2
`

type GetWalletParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetWallet(ctx context.Context, arg GetWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWallet, arg.UserID, arg.ID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Provider,
		&i.InitialBalance,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletWithBalance = `-- name: GetWalletWithBalance :one
SELECT w.id, w.user_id, w.name, w.type, w.provider, w.initial_balance, w.archived_at, w.created_at,
       (w.initial_balance + COALESCE(SUM(
           CASE WHEN t.kind = 'income' THEN t.amount ELSE -t.amount END
       ), 0))::bigint AS balance
FROM wallets w
LEFT JOIN transactions t
       ON t.wallet_id = w.id AND t.user_id = w.user_id AND t.deleted_at IS NULL
WHERE w.user_id = $1 AND w.id = $2
GROUP BY w.id
`

type GetWalletWithBalanceParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

type GetWalletWithBalanceRow struct {
	ID             uuid.UUID  `json:"id"`
	UserID         uuid.UUID  `json:"user_id"`
	Name           string     `json:"name"`
	Type           string     `json:"type"`
	Provider       *string    `json:"provider"`
	InitialBalance int64      `json:"initial_balance"`
	ArchivedAt     *time.Time `json:"archived_at"`
	CreatedAt      time.Time  `json:"created_at"`
	Balance        int64      `json:"balance"`
}

func (q *Queries) GetWalletWithBalance(ctx context.Context, arg GetWalletWithBalanceParams) (GetWalletWithBalanceRow, error) {
	row := q.db.QueryRow(ctx, getWalletWithBalance, arg.UserID, arg.ID)
	var i GetWalletWithBalanceRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Provider,
		&i.InitialBalance,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.Balance,
	)
	return i, err
}

const listWalletsWithBalance = `-- name: ListWalletsWithBalance :many
SELECT w.id, w.user_id, w.name, w.type, w.provider, w.initial_balance, w.archived_at, w.created_at,
       (w.initial_balance + COALESCE(SUM(
           CASE WHEN t.kind = 'income' THEN t.amount ELSE -t.amount END
       ), 0))::bigint AS balance
FROM wallets w
LEFT JOIN transactions t
       ON t.wallet_id = w.id AND t.user_id = w.user_id AND t.deleted_at IS NULL
WHERE w.user_id = $1
  AND ($2::boolean OR w.archived_at IS NULL)
GROUP BY w.id
ORDER BY w.archived_at NULLS FIRST, w.created_at
`

type ListWalletsWithBalanceParams struct {
	UserID          uuid.UUID `json:"user_id"`
	IncludeArchived bool      `json:"include_archived"`
}

type ListWalletsWithBalanceRow struct {
	ID             uuid.UUID  `json:"id"`
	UserID         uuid.UUID  `json:"user_id"`
	Name           string     `json:"name"`
	Type           string     `json:"type"`
	Provider       *string    `json:"provider"`
	InitialBalance int64      `json:"initial_balance"`
	ArchivedAt     *time.Time `json:"archived_at"`
	CreatedAt      time.Time  `json:"created_at"`
	Balance        int64      `json:"balance"`
}

// Saldo = saldo awal + pemasukan − pengeluaran (transaksi yang tidak dihapus).
func (q *Queries) ListWalletsWithBalance(ctx context.Context, arg ListWalletsWithBalanceParams) ([]ListWalletsWithBalanceRow, error) {
	rows, err := q.db.Query(ctx, listWalletsWithBalance, arg.UserID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWalletsWithBalanceRow{}
	for rows.Next() {
		var i ListWalletsWithBalanceRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Provider,
			&i.InitialBalance,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWallet = `-- name: UpdateWallet :one
UPDATE wallets
SET name = $1,
    type = $2,
    provider = $3,
    initial_balance = $4,
    archived_at = $5
WHERE user_id = $6 AND id = $7
RETURNING id, user_id, name, type, provider, initial_balance, archived_at, created_at
`

type UpdateWalletParams struct {
	Name           string     `json:"name"`
	Type           string     `json:"type"`
	Provider       *string    `json:"provider"`
	InitialBalance int64      `json:"initial_balance"`
	ArchivedAt     *time.Time `json:"archived_at"`
	UserID         uuid.UUID  `json:"user_id"`
	ID             uuid.UUID  `json:"id"`
}

func (q *Queries) UpdateWallet(ctx context.Context, arg UpdateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, updateWallet,
		arg.Name,
		arg.Type,
		arg.Provider,
		arg.InitialBalance,
		arg.ArchivedAt,
		arg.UserID,
		arg.ID,
	)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Provider,
		&i.InitialBalance,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}
