// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import (
	"time"

	"github.com/oapi-codegen/nullable"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BudgetStatus.
const (
	Near BudgetStatus = "near"
	Over BudgetStatus = "over"
	Safe BudgetStatus = "safe"
)

// Valid indicates whether the value is a known member of the BudgetStatus enum.
func (e BudgetStatus) Valid() bool {
	switch e {
	case Near:
		return true
	case Over:
		return true
	case Safe:
		return true
	default:
		return false
	}
}

// Defines values for HealthDb.
const (
	HealthDbOk HealthDb = "ok"
)

// Valid indicates whether the value is a known member of the HealthDb enum.
func (e HealthDb) Valid() bool {
	switch e {
	case HealthDbOk:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusOk HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for Kind.
const (
	Expense Kind = "expense"
	Income  Kind = "income"
)

// Valid indicates whether the value is a known member of the Kind enum.
func (e Kind) Valid() bool {
	switch e {
	case Expense:
		return true
	case Income:
		return true
	default:
		return false
	}
}

// Defines values for TransactionSource.
const (
	Import  TransactionSource = "import"
	Manual  TransactionSource = "manual"
	Receipt TransactionSource = "receipt"
)

// Valid indicates whether the value is a known member of the TransactionSource enum.
func (e TransactionSource) Valid() bool {
	switch e {
	case Import:
		return true
	case Manual:
		return true
	case Receipt:
		return true
	default:
		return false
	}
}

// Defines values for UpdateMeRequestTheme.
const (
	UpdateMeRequestThemeDark   UpdateMeRequestTheme = "dark"
	UpdateMeRequestThemeLight  UpdateMeRequestTheme = "light"
	UpdateMeRequestThemeSystem UpdateMeRequestTheme = "system"
)

// Valid indicates whether the value is a known member of the UpdateMeRequestTheme enum.
func (e UpdateMeRequestTheme) Valid() bool {
	switch e {
	case UpdateMeRequestThemeDark:
		return true
	case UpdateMeRequestThemeLight:
		return true
	case UpdateMeRequestThemeSystem:
		return true
	default:
		return false
	}
}

// Defines values for UserTheme.
const (
	UserThemeDark   UserTheme = "dark"
	UserThemeLight  UserTheme = "light"
	UserThemeSystem UserTheme = "system"
)

// Valid indicates whether the value is a known member of the UserTheme enum.
func (e UserTheme) Valid() bool {
	switch e {
	case UserThemeDark:
		return true
	case UserThemeLight:
		return true
	case UserThemeSystem:
		return true
	default:
		return false
	}
}

// Defines values for WalletType.
const (
	Bank    WalletType = "bank"
	Cash    WalletType = "cash"
	Ewallet WalletType = "ewallet"
	Other   WalletType = "other"
)

// Valid indicates whether the value is a known member of the WalletType enum.
func (e WalletType) Valid() bool {
	switch e {
	case Bank:
		return true
	case Cash:
		return true
	case Ewallet:
		return true
	case Other:
		return true
	default:
		return false
	}
}

// Defines values for XRequestedWith.
const (
	XRequestedWithFundly XRequestedWith = "fundly"
)

// Valid indicates whether the value is a known member of the XRequestedWith enum.
func (e XRequestedWith) Valid() bool {
	switch e {
	case XRequestedWithFundly:
		return true
	default:
		return false
	}
}

// Defines values for LoginParamsXRequestedWith.
const (
	LoginParamsXRequestedWithFundly LoginParamsXRequestedWith = "fundly"
)

// Valid indicates whether the value is a known member of the LoginParamsXRequestedWith enum.
func (e LoginParamsXRequestedWith) Valid() bool {
	switch e {
	case LoginParamsXRequestedWithFundly:
		return true
	default:
		return false
	}
}

// Defines values for LogoutParamsXRequestedWith.
const (
	LogoutParamsXRequestedWithFundly LogoutParamsXRequestedWith = "fundly"
)

// Valid indicates whether the value is a known member of the LogoutParamsXRequestedWith enum.
func (e LogoutParamsXRequestedWith) Valid() bool {
	switch e {
	case LogoutParamsXRequestedWithFundly:
		return true
	default:
		return false
	}
}

// Defines values for RegisterParamsXRequestedWith.
const (
	RegisterParamsXRequestedWithFundly RegisterParamsXRequestedWith = "fundly"
)

// Valid indicates whether the value is a known member of the RegisterParamsXRequestedWith enum.
func (e RegisterParamsXRequestedWith) Valid() bool {
	switch e {
	case RegisterParamsXRequestedWithFundly:
		return true
	default:
		return false
	}
}

// Defines values for DeleteBudgetParamsXRequestedWith.
const (
	DeleteBudgetParamsXRequestedWithFundly DeleteBudgetParamsXRequestedWith = "fundly"
)

// Valid indicates whether the value is a known member of the DeleteBudgetParamsXRequestedWith enum.
func (e DeleteBudgetParamsXRequestedWith) Valid() bool {
	switch e {
	case DeleteBudgetParamsXRequestedWithFundly:
		return true
	default:
		return false
	}
}

// Defines values for PutBudgetParamsXRequestedWith.
const (
	PutBudgetParamsXRequestedWithFundly PutBudgetParamsXRequestedWith = "fundly"
)

// Valid indicates whether the value is a known member of the PutBudgetParamsXRequestedWith enum.
func (e PutBudgetParamsXRequestedWith) Valid() bool {
	switch e {
	case PutBudgetParamsXRequestedWithFundly:
		return true
	default:
		return false
	}
}

// Defines values for CreateCategoryParamsXRequestedWith.
const (
	CreateCategoryParamsXRequestedWithFundly CreateCategoryParamsXRequestedWith = "fundly"
)

// Valid indicates whether the value is a known member of the CreateCategoryParamsXRequestedWith enum.
func (e CreateCategoryParamsXRequestedWith) Valid() bool {
	switch e {
	case CreateCategoryParamsXRequestedWithFundly:
		return true
	default:
		return false
	}
}

// Defines values for SuggestCategoryParamsXRequestedWith.
const (
	SuggestCategoryParamsXRequestedWithFundly SuggestCategoryParamsXRequestedWith = "fundly"
)

// Valid indicates whether the value is a known member of the SuggestCategoryParamsXRequestedWith enum.
func (e SuggestCategoryParamsXRequestedWith) Valid() bool {
	switch e {
	case SuggestCategoryParamsXRequestedWithFundly:
		return true
	default:
		return false
	}
}

// Defines values for UpdateCategoryParamsXRequestedWith.
const (
	UpdateCategoryParamsXRequestedWithFundly UpdateCategoryParamsXRequestedWith = "fundly"
)

// Valid indicates whether the value is a known member of the UpdateCategoryParamsXRequestedWith enum.
func (e UpdateCategoryParamsXRequestedWith) Valid() bool {
	switch e {
	case UpdateCategoryParamsXRequestedWithFundly:
		return true
	default:
		return false
	}
}

// Defines values for DeleteMeParamsXRequestedWith.
const (
	DeleteMeParamsXRequestedWithFundly DeleteMeParamsXRequestedWith = "fundly"
)

// Valid indicates whether the value is a known member of the DeleteMeParamsXRequestedWith enum.
func (e DeleteMeParamsXRequestedWith) Valid() bool {
	switch e {
	case DeleteMeParamsXRequestedWithFundly:
		return true
	default:
		return false
	}
}

// Defines values for DeleteMeJSONBodyConfirm.
const (
	HAPUS DeleteMeJSONBodyConfirm = "HAPUS"
)

// Valid indicates whether the value is a known member of the DeleteMeJSONBodyConfirm enum.
func (e DeleteMeJSONBodyConfirm) Valid() bool {
	switch e {
	case HAPUS:
		return true
	default:
		return false
	}
}

// Defines values for UpdateMeParamsXRequestedWith.
const (
	UpdateMeParamsXRequestedWithFundly UpdateMeParamsXRequestedWith = "fundly"
)

// Valid indicates whether the value is a known member of the UpdateMeParamsXRequestedWith enum.
func (e UpdateMeParamsXRequestedWith) Valid() bool {
	switch e {
	case UpdateMeParamsXRequestedWithFundly:
		return true
	default:
		return false
	}
}

// Defines values for CreateTransactionParamsXRequestedWith.
const (
	CreateTransactionParamsXRequestedWithFundly CreateTransactionParamsXRequestedWith = "fundly"
)

// Valid indicates whether the value is a known member of the CreateTransactionParamsXRequestedWith enum.
func (e CreateTransactionParamsXRequestedWith) Valid() bool {
	switch e {
	case CreateTransactionParamsXRequestedWithFundly:
		return true
	default:
		return false
	}
}

// Defines values for DeleteTransactionParamsXRequestedWith.
const (
	DeleteTransactionParamsXRequestedWithFundly DeleteTransactionParamsXRequestedWith = "fundly"
)

// Valid indicates whether the value is a known member of the DeleteTransactionParamsXRequestedWith enum.
func (e DeleteTransactionParamsXRequestedWith) Valid() bool {
	switch e {
	case DeleteTransactionParamsXRequestedWithFundly:
		return true
	default:
		return false
	}
}

// Defines values for UpdateTransactionParamsXRequestedWith.
const (
	UpdateTransactionParamsXRequestedWithFundly UpdateTransactionParamsXRequestedWith = "fundly"
)

// Valid indicates whether the value is a known member of the UpdateTransactionParamsXRequestedWith enum.
func (e UpdateTransactionParamsXRequestedWith) Valid() bool {
	switch e {
	case UpdateTransactionParamsXRequestedWithFundly:
		return true
	default:
		return false
	}
}

// Defines values for RestoreTransactionParamsXRequestedWith.
const (
	RestoreTransactionParamsXRequestedWithFundly RestoreTransactionParamsXRequestedWith = "fundly"
)

// Valid indicates whether the value is a known member of the RestoreTransactionParamsXRequestedWith enum.
func (e RestoreTransactionParamsXRequestedWith) Valid() bool {
	switch e {
	case RestoreTransactionParamsXRequestedWithFundly:
		return true
	default:
		return false
	}
}

// Defines values for CreateWalletParamsXRequestedWith.
const (
	CreateWalletParamsXRequestedWithFundly CreateWalletParamsXRequestedWith = "fundly"
)

// Valid indicates whether the value is a known member of the CreateWalletParamsXRequestedWith enum.
func (e CreateWalletParamsXRequestedWith) Valid() bool {
	switch e {
	case CreateWalletParamsXRequestedWithFundly:
		return true
	default:
		return false
	}
}

// Defines values for UpdateWalletParamsXRequestedWith.
const (
	UpdateWalletParamsXRequestedWithFundly UpdateWalletParamsXRequestedWith = "fundly"
)

// Valid indicates whether the value is a known member of the UpdateWalletParamsXRequestedWith enum.
func (e UpdateWalletParamsXRequestedWith) Valid() bool {
	switch e {
	case UpdateWalletParamsXRequestedWithFundly:
		return true
	default:
		return false
	}
}

// Budget defines model for Budget.
type Budget struct {
	CategoryId openapi_types.UUID `json:"category_id"`

	// LimitAmount Jumlah rupiah tanpa desimal
	LimitAmount Money  `json:"limit_amount"`
	Month       string `json:"month"`

	// Spent Jumlah rupiah tanpa desimal
	Spent Money `json:"spent"`

	// Status safe < 80%, near ≥ 80%, over ≥ 100%
	Status BudgetStatus `json:"status"`
}

// BudgetStatus safe < 80%, near ≥ 80%, over ≥ 100%
type BudgetStatus string

// Category defines model for Category.
type Category struct {
	ColorToken string             `json:"color_token"`
	Hidden     bool               `json:"hidden"`
	Icon       string             `json:"icon"`
	Id         openapi_types.UUID `json:"id"`

	// IsSystem true untuk kategori bawaan
	IsSystem  bool   `json:"is_system"`
	Kind      Kind   `json:"kind"`
	Name      string `json:"name"`
	SortOrder int    `json:"sort_order"`
}

// CategoryCreate defines model for CategoryCreate.
type CategoryCreate struct {
	ColorToken *string `json:"color_token,omitempty"`
	Icon       *string `json:"icon,omitempty"`
	Kind       Kind    `json:"kind"`
	Name       string  `json:"name"`
}

// CategoryUpdate defines model for CategoryUpdate.
type CategoryUpdate struct {
	ColorToken *string `json:"color_token,omitempty"`
	Hidden     *bool   `json:"hidden,omitempty"`
	Icon       *string `json:"icon,omitempty"`
	Name       *string `json:"name,omitempty"`
	SortOrder  *int    `json:"sort_order,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Db     HealthDb     `json:"db"`
	Status HealthStatus `json:"status"`
}

// HealthDb defines model for Health.Db.
type HealthDb string

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Kind defines model for Kind.
type Kind string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Money Jumlah rupiah tanpa desimal
type Money = int64

// MonthlyReport defines model for MonthlyReport.
type MonthlyReport struct {
	AvgDailyExpense int64 `json:"avg_daily_expense"`
	ByCategory      []struct {
		Amount     int64                                 `json:"amount"`
		CategoryId nullable.Nullable[openapi_types.UUID] `json:"category_id"`
		Name       string                                `json:"name"`
		Percent    float32                               `json:"percent"`
	} `json:"by_category"`
	Daily []struct {
		Date    openapi_types.Date `json:"date"`
		Expense int64              `json:"expense"`
		Income  int64              `json:"income"`
	} `json:"daily"`
	Month    string `json:"month"`
	Net      int64  `json:"net"`
	Previous struct {
		ExpenseChangePercent nullable.Nullable[float32] `json:"expense_change_percent"`
		TotalExpense         int64                      `json:"total_expense"`
		TotalIncome          int64                      `json:"total_income"`
	} `json:"previous"`
	TotalExpense int64 `json:"total_expense"`
	TotalIncome  int64 `json:"total_income"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName *string             `json:"display_name,omitempty"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	Amount     int64                                 `json:"amount"`
	CategoryId nullable.Nullable[openapi_types.UUID] `json:"category_id"`
	ClientId   nullable.Nullable[openapi_types.UUID] `json:"client_id"`
	CreatedAt  time.Time                             `json:"created_at"`
	Id         openapi_types.UUID                    `json:"id"`
	Kind       Kind                                  `json:"kind"`
	Merchant   nullable.Nullable[string]             `json:"merchant"`
	Note       nullable.Nullable[string]             `json:"note"`
	OccurredOn openapi_types.Date                    `json:"occurred_on"`
	Source     TransactionSource                     `json:"source"`
	UpdatedAt  time.Time                             `json:"updated_at"`
	WalletId   openapi_types.UUID                    `json:"wallet_id"`
}

// TransactionSource defines model for Transaction.Source.
type TransactionSource string

// TransactionCreate defines model for TransactionCreate.
type TransactionCreate struct {
	Amount     int64                                 `json:"amount"`
	CategoryId nullable.Nullable[openapi_types.UUID] `json:"category_id,omitempty"`

	// ClientId Kunci idempoten dari klien (antrean offline, F-07)
	ClientId   nullable.Nullable[openapi_types.UUID] `json:"client_id,omitempty"`
	Kind       Kind                                  `json:"kind"`
	Merchant   nullable.Nullable[string]             `json:"merchant,omitempty"`
	Note       nullable.Nullable[string]             `json:"note,omitempty"`
	OccurredOn openapi_types.Date                    `json:"occurred_on"`
	WalletId   openapi_types.UUID                    `json:"wallet_id"`
}

// TransactionUpdate defines model for TransactionUpdate.
type TransactionUpdate struct {
	Amount     *int64                                `json:"amount,omitempty"`
	CategoryId nullable.Nullable[openapi_types.UUID] `json:"category_id,omitempty"`
	Kind       *Kind                                 `json:"kind,omitempty"`
	Merchant   nullable.Nullable[string]             `json:"merchant,omitempty"`
	Note       nullable.Nullable[string]             `json:"note,omitempty"`
	OccurredOn *openapi_types.Date                   `json:"occurred_on,omitempty"`
	WalletId   *openapi_types.UUID                   `json:"wallet_id,omitempty"`
}

// UpdateMeRequest defines model for UpdateMeRequest.
type UpdateMeRequest struct {
	BudgetAutoCopy  *bool                 `json:"budget_auto_copy,omitempty"`
	CurrentPassword *string               `json:"current_password,omitempty"`
	DisplayName     *string               `json:"display_name,omitempty"`
	NewPassword     *string               `json:"new_password,omitempty"`
	Theme           *UpdateMeRequestTheme `json:"theme,omitempty"`
}

// UpdateMeRequestTheme defines model for UpdateMeRequest.Theme.
type UpdateMeRequestTheme string

// User defines model for User.
type User struct {
	// BudgetAutoCopy Anggaran bulan baru otomatis menyalin bulan lalu (F-06 KP3)
	BudgetAutoCopy bool                `json:"budget_auto_copy"`
	CreatedAt      time.Time           `json:"created_at"`
	DisplayName    string              `json:"display_name"`
	Email          openapi_types.Email `json:"email"`
	HasGoogle      bool                `json:"has_google"`
	HasPassword    bool                `json:"has_password"`
	Id             openapi_types.UUID  `json:"id"`
	Theme          UserTheme           `json:"theme"`
}

// UserTheme defines model for User.Theme.
type UserTheme string

// Wallet defines model for Wallet.
type Wallet struct {
	ArchivedAt nullable.Nullable[time.Time] `json:"archived_at"`

	// Balance Saldo awal + pemasukan − pengeluaran
	Balance        int64                     `json:"balance"`
	CreatedAt      time.Time                 `json:"created_at"`
	Id             openapi_types.UUID        `json:"id"`
	InitialBalance int64                     `json:"initial_balance"`
	Name           string                    `json:"name"`
	Provider       nullable.Nullable[string] `json:"provider"`
	Type           WalletType                `json:"type"`
}

// WalletCreate defines model for WalletCreate.
type WalletCreate struct {
	InitialBalance *int64                    `json:"initial_balance,omitempty"`
	Name           string                    `json:"name"`
	Provider       nullable.Nullable[string] `json:"provider,omitempty"`
	Type           WalletType                `json:"type"`
}

// WalletType defines model for WalletType.
type WalletType string

// WalletUpdate defines model for WalletUpdate.
type WalletUpdate struct {
	Archived       *bool                     `json:"archived,omitempty"`
	InitialBalance *int64                    `json:"initial_balance,omitempty"`
	Name           *string                   `json:"name,omitempty"`
	Provider       nullable.Nullable[string] `json:"provider,omitempty"`
	Type           *WalletType               `json:"type,omitempty"`
}

// Id defines model for Id.
type Id = openapi_types.UUID

// Month defines model for Month.
type Month = string

// MonthRequired defines model for MonthRequired.
type MonthRequired = string

// XRequestedWith defines model for XRequestedWith.
type XRequestedWith string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// Unprocessable defines model for Unprocessable.
type Unprocessable = Error

// GoogleCallbackParams defines parameters for GoogleCallback.
type GoogleCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// LoginParams defines parameters for Login.
type LoginParams struct {
	// XRequestedWith Lapisan CSRF tambahan untuk permintaan yang mengubah data
	XRequestedWith LoginParamsXRequestedWith `json:"X-Requested-With"`
}

// LoginParamsXRequestedWith defines parameters for Login.
type LoginParamsXRequestedWith string

// LogoutParams defines parameters for Logout.
type LogoutParams struct {
	// XRequestedWith Lapisan CSRF tambahan untuk permintaan yang mengubah data
	XRequestedWith LogoutParamsXRequestedWith `json:"X-Requested-With"`
}

// LogoutParamsXRequestedWith defines parameters for Logout.
type LogoutParamsXRequestedWith string

// RegisterParams defines parameters for Register.
type RegisterParams struct {
	// XRequestedWith Lapisan CSRF tambahan untuk permintaan yang mengubah data
	XRequestedWith RegisterParamsXRequestedWith `json:"X-Requested-With"`
}

// RegisterParamsXRequestedWith defines parameters for Register.
type RegisterParamsXRequestedWith string

// ListBudgetsParams defines parameters for ListBudgets.
type ListBudgetsParams struct {
	// Month Bulan dalam format YYYY-MM
	Month MonthRequired `form:"month" json:"month"`
}

// DeleteBudgetParams defines parameters for DeleteBudget.
type DeleteBudgetParams struct {
	// Month Bulan dalam format YYYY-MM
	Month MonthRequired `form:"month" json:"month"`

	// XRequestedWith Lapisan CSRF tambahan untuk permintaan yang mengubah data
	XRequestedWith DeleteBudgetParamsXRequestedWith `json:"X-Requested-With"`
}

// DeleteBudgetParamsXRequestedWith defines parameters for DeleteBudget.
type DeleteBudgetParamsXRequestedWith string

// PutBudgetJSONBody defines parameters for PutBudget.
type PutBudgetJSONBody struct {
	// LimitAmount Jumlah rupiah tanpa desimal
	LimitAmount Money `json:"limit_amount"`
}

// PutBudgetParams defines parameters for PutBudget.
type PutBudgetParams struct {
	// Month Bulan dalam format YYYY-MM
	Month MonthRequired `form:"month" json:"month"`

	// XRequestedWith Lapisan CSRF tambahan untuk permintaan yang mengubah data
	XRequestedWith PutBudgetParamsXRequestedWith `json:"X-Requested-With"`
}

// PutBudgetParamsXRequestedWith defines parameters for PutBudget.
type PutBudgetParamsXRequestedWith string

// ListCategoriesParams defines parameters for ListCategories.
type ListCategoriesParams struct {
	Kind          *Kind `form:"kind,omitempty" json:"kind,omitempty"`
	IncludeHidden *bool `form:"include_hidden,omitempty" json:"include_hidden,omitempty"`
}

// CreateCategoryParams defines parameters for CreateCategory.
type CreateCategoryParams struct {
	// XRequestedWith Lapisan CSRF tambahan untuk permintaan yang mengubah data
	XRequestedWith CreateCategoryParamsXRequestedWith `json:"X-Requested-With"`
}

// CreateCategoryParamsXRequestedWith defines parameters for CreateCategory.
type CreateCategoryParamsXRequestedWith string

// SuggestCategoryJSONBody defines parameters for SuggestCategory.
type SuggestCategoryJSONBody struct {
	Kind     *Kind                     `json:"kind,omitempty"`
	Merchant nullable.Nullable[string] `json:"merchant,omitempty"`
	Note     nullable.Nullable[string] `json:"note,omitempty"`
}

// SuggestCategoryParams defines parameters for SuggestCategory.
type SuggestCategoryParams struct {
	// XRequestedWith Lapisan CSRF tambahan untuk permintaan yang mengubah data
	XRequestedWith SuggestCategoryParamsXRequestedWith `json:"X-Requested-With"`
}

// SuggestCategoryParamsXRequestedWith defines parameters for SuggestCategory.
type SuggestCategoryParamsXRequestedWith string

// UpdateCategoryParams defines parameters for UpdateCategory.
type UpdateCategoryParams struct {
	// XRequestedWith Lapisan CSRF tambahan untuk permintaan yang mengubah data
	XRequestedWith UpdateCategoryParamsXRequestedWith `json:"X-Requested-With"`
}

// UpdateCategoryParamsXRequestedWith defines parameters for UpdateCategory.
type UpdateCategoryParamsXRequestedWith string

// ExportTransactionsCsvParams defines parameters for ExportTransactionsCsv.
type ExportTransactionsCsvParams struct {
	// Month Bulan dalam format YYYY-MM (default bulan ini, zona Asia/Jakarta)
	Month *Month `form:"month,omitempty" json:"month,omitempty"`
}

// DeleteMeJSONBody defines parameters for DeleteMe.
type DeleteMeJSONBody struct {
	// Confirm Konfirmasi eksplisit
	Confirm DeleteMeJSONBodyConfirm `json:"confirm"`
}

// DeleteMeParams defines parameters for DeleteMe.
type DeleteMeParams struct {
	// XRequestedWith Lapisan CSRF tambahan untuk permintaan yang mengubah data
	XRequestedWith DeleteMeParamsXRequestedWith `json:"X-Requested-With"`
}

// DeleteMeParamsXRequestedWith defines parameters for DeleteMe.
type DeleteMeParamsXRequestedWith string

// DeleteMeJSONBodyConfirm defines parameters for DeleteMe.
type DeleteMeJSONBodyConfirm string

// UpdateMeParams defines parameters for UpdateMe.
type UpdateMeParams struct {
	// XRequestedWith Lapisan CSRF tambahan untuk permintaan yang mengubah data
	XRequestedWith UpdateMeParamsXRequestedWith `json:"X-Requested-With"`
}

// UpdateMeParamsXRequestedWith defines parameters for UpdateMe.
type UpdateMeParamsXRequestedWith string

// GetMonthlyReportParams defines parameters for GetMonthlyReport.
type GetMonthlyReportParams struct {
	// Month Bulan dalam format YYYY-MM
	Month MonthRequired `form:"month" json:"month"`
}

// ListTransactionsParams defines parameters for ListTransactions.
type ListTransactionsParams struct {
	// Month Bulan dalam format YYYY-MM (default bulan ini, zona Asia/Jakarta)
	Month      *Month              `form:"month,omitempty" json:"month,omitempty"`
	WalletId   *openapi_types.UUID `form:"wallet_id,omitempty" json:"wallet_id,omitempty"`
	CategoryId *openapi_types.UUID `form:"category_id,omitempty" json:"category_id,omitempty"`
	Kind       *Kind               `form:"kind,omitempty" json:"kind,omitempty"`
	Q          *string             `form:"q,omitempty" json:"q,omitempty"`
	Cursor     *string             `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit      *int                `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateTransactionParams defines parameters for CreateTransaction.
type CreateTransactionParams struct {
	// XRequestedWith Lapisan CSRF tambahan untuk permintaan yang mengubah data
	XRequestedWith CreateTransactionParamsXRequestedWith `json:"X-Requested-With"`
}

// CreateTransactionParamsXRequestedWith defines parameters for CreateTransaction.
type CreateTransactionParamsXRequestedWith string

// DeleteTransactionParams defines parameters for DeleteTransaction.
type DeleteTransactionParams struct {
	// XRequestedWith Lapisan CSRF tambahan untuk permintaan yang mengubah data
	XRequestedWith DeleteTransactionParamsXRequestedWith `json:"X-Requested-With"`
}

// DeleteTransactionParamsXRequestedWith defines parameters for DeleteTransaction.
type DeleteTransactionParamsXRequestedWith string

// UpdateTransactionParams defines parameters for UpdateTransaction.
type UpdateTransactionParams struct {
	// XRequestedWith Lapisan CSRF tambahan untuk permintaan yang mengubah data
	XRequestedWith UpdateTransactionParamsXRequestedWith `json:"X-Requested-With"`
}

// UpdateTransactionParamsXRequestedWith defines parameters for UpdateTransaction.
type UpdateTransactionParamsXRequestedWith string

// RestoreTransactionParams defines parameters for RestoreTransaction.
type RestoreTransactionParams struct {
	// XRequestedWith Lapisan CSRF tambahan untuk permintaan yang mengubah data
	XRequestedWith RestoreTransactionParamsXRequestedWith `json:"X-Requested-With"`
}

// RestoreTransactionParamsXRequestedWith defines parameters for RestoreTransaction.
type RestoreTransactionParamsXRequestedWith string

// ListWalletsParams defines parameters for ListWallets.
type ListWalletsParams struct {
	IncludeArchived *bool `form:"include_archived,omitempty" json:"include_archived,omitempty"`
}

// CreateWalletParams defines parameters for CreateWallet.
type CreateWalletParams struct {
	// XRequestedWith Lapisan CSRF tambahan untuk permintaan yang mengubah data
	XRequestedWith CreateWalletParamsXRequestedWith `json:"X-Requested-With"`
}

// CreateWalletParamsXRequestedWith defines parameters for CreateWallet.
type CreateWalletParamsXRequestedWith string

// UpdateWalletParams defines parameters for UpdateWallet.
type UpdateWalletParams struct {
	// XRequestedWith Lapisan CSRF tambahan untuk permintaan yang mengubah data
	XRequestedWith UpdateWalletParamsXRequestedWith `json:"X-Requested-With"`
}

// UpdateWalletParamsXRequestedWith defines parameters for UpdateWallet.
type UpdateWalletParamsXRequestedWith string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// PutBudgetJSONRequestBody defines body for PutBudget for application/json ContentType.
type PutBudgetJSONRequestBody PutBudgetJSONBody

// CreateCategoryJSONRequestBody defines body for CreateCategory for application/json ContentType.
type CreateCategoryJSONRequestBody = CategoryCreate

// SuggestCategoryJSONRequestBody defines body for SuggestCategory for application/json ContentType.
type SuggestCategoryJSONRequestBody SuggestCategoryJSONBody

// UpdateCategoryJSONRequestBody defines body for UpdateCategory for application/json ContentType.
type UpdateCategoryJSONRequestBody = CategoryUpdate

// DeleteMeJSONRequestBody defines body for DeleteMe for application/json ContentType.
type DeleteMeJSONRequestBody DeleteMeJSONBody

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateMeRequest

// CreateTransactionJSONRequestBody defines body for CreateTransaction for application/json ContentType.
type CreateTransactionJSONRequestBody = TransactionCreate

// UpdateTransactionJSONRequestBody defines body for UpdateTransaction for application/json ContentType.
type UpdateTransactionJSONRequestBody = TransactionUpdate

// CreateWalletJSONRequestBody defines body for CreateWallet for application/json ContentType.
type CreateWalletJSONRequestBody = WalletCreate

// UpdateWalletJSONRequestBody defines body for UpdateWallet for application/json ContentType.
type UpdateWalletJSONRequestBody = WalletUpdate
