/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cek kesehatan dan SELECT 1 ke database (publik) */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Daftar dengan email dan password (publik) */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Masuk dengan email dan password (publik) */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Keluar dan hapus sesi di server */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mulai OAuth Google (publik) */
        get: operations["googleStart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Callback OAuth Google (publik) */
        get: operations["googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profil dan pengaturan */
        get: operations["getMe"];
        put?: never;
        post?: never;
        /** Hapus akun dan semua data secara permanen */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        /** Ubah profil, tema, atau password */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/wallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar dompet beserta saldo sekarang */
        get: operations["listWallets"];
        put?: never;
        /** Buat dompet */
        post: operations["createWallet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Ubah atau arsipkan dompet */
        patch: operations["updateWallet"];
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar kategori (bawaan dan milik pengguna) */
        get: operations["listCategories"];
        put?: never;
        /** Buat kategori */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Ubah atau sembunyikan kategori */
        patch: operations["updateCategory"];
        trace?: never;
    };
    "/categories/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Saran kategori dari nama merchant atau catatan */
        post: operations["suggestCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar transaksi (paginasi kursor) */
        get: operations["listTransactions"];
        put?: never;
        /** Buat transaksi (idempoten lewat client_id) */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Detail transaksi */
        get: operations["getTransaction"];
        put?: never;
        post?: never;
        /** Hapus transaksi (soft delete) */
        delete: operations["deleteTransaction"];
        options?: never;
        head?: never;
        /** Ubah transaksi */
        patch: operations["updateTransaction"];
        trace?: never;
    };
    "/transactions/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batalkan hapus */
        post: operations["restoreTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Laporan bulanan */
        get: operations["getMonthlyReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Anggaran bulan beserta jumlah terpakai */
        get: operations["listBudgets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Atur batas anggaran kategori untuk satu bulan */
        put: operations["putBudget"];
        post?: never;
        /** Hapus batas anggaran kategori untuk satu bulan */
        delete: operations["deleteBudget"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/transactions.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ekspor transaksi ke CSV (bulan tertentu, atau semua bila month kosong) */
        get: operations["exportTransactionsCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: int64
         * @description Jumlah rupiah tanpa desimal
         */
        Money: number;
        /** @enum {string} */
        Kind: "expense" | "income";
        Error: {
            error: {
                code: string;
                message: string;
            };
        };
        Health: {
            /** @constant */
            status: "ok";
            /** @constant */
            db: "ok";
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            /** @enum {string} */
            theme: "system" | "light" | "dark";
            /** @description Anggaran bulan baru otomatis menyalin bulan lalu (F-06 KP3) */
            budget_auto_copy: boolean;
            has_password: boolean;
            has_google: boolean;
            /** Format: date-time */
            created_at: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            display_name?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        UpdateMeRequest: {
            display_name?: string;
            /** @enum {string} */
            theme?: "system" | "light" | "dark";
            budget_auto_copy?: boolean;
            current_password?: string;
            new_password?: string;
        };
        /** @enum {string} */
        WalletType: "cash" | "bank" | "ewallet" | "other";
        Wallet: {
            /** Format: uuid */
            id: string;
            name: string;
            type: components["schemas"]["WalletType"];
            provider: string | null;
            /** Format: int64 */
            initial_balance: number;
            /**
             * Format: int64
             * @description Saldo awal + pemasukan − pengeluaran
             */
            balance: number;
            /** Format: date-time */
            archived_at: string | null;
            /** Format: date-time */
            created_at: string;
        };
        WalletCreate: {
            name: string;
            type: components["schemas"]["WalletType"];
            provider?: string | null;
            /**
             * Format: int64
             * @default 0
             */
            initial_balance: number;
        };
        WalletUpdate: {
            name?: string;
            type?: components["schemas"]["WalletType"];
            provider?: string | null;
            /** Format: int64 */
            initial_balance?: number;
            archived?: boolean;
        };
        Category: {
            /** Format: uuid */
            id: string;
            name: string;
            kind: components["schemas"]["Kind"];
            icon: string;
            color_token: string;
            sort_order: number;
            hidden: boolean;
            /** @description true untuk kategori bawaan */
            is_system: boolean;
        };
        CategoryCreate: {
            name: string;
            kind: components["schemas"]["Kind"];
            icon?: string;
            color_token?: string;
        };
        CategoryUpdate: {
            name?: string;
            icon?: string;
            color_token?: string;
            sort_order?: number;
            hidden?: boolean;
        };
        Transaction: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            wallet_id: string;
            /** Format: uuid */
            category_id: string | null;
            kind: components["schemas"]["Kind"];
            /** Format: int64 */
            amount: number;
            /** Format: date */
            occurred_on: string;
            merchant: string | null;
            note: string | null;
            /** @enum {string} */
            source: "manual" | "receipt" | "import";
            /** Format: uuid */
            client_id: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TransactionCreate: {
            /** Format: uuid */
            wallet_id: string;
            /** Format: uuid */
            category_id?: string | null;
            kind: components["schemas"]["Kind"];
            /** Format: int64 */
            amount: number;
            /** Format: date */
            occurred_on: string;
            merchant?: string | null;
            note?: string | null;
            /**
             * Format: uuid
             * @description Kunci idempoten dari klien (antrean offline, F-07)
             */
            client_id?: string | null;
        };
        TransactionUpdate: {
            /** Format: uuid */
            wallet_id?: string;
            /** Format: uuid */
            category_id?: string | null;
            kind?: components["schemas"]["Kind"];
            /** Format: int64 */
            amount?: number;
            /** Format: date */
            occurred_on?: string;
            merchant?: string | null;
            note?: string | null;
        };
        MonthlyReport: {
            month: string;
            /** Format: int64 */
            total_income: number;
            /** Format: int64 */
            total_expense: number;
            /** Format: int64 */
            net: number;
            /** Format: int64 */
            avg_daily_expense: number;
            by_category: {
                /** Format: uuid */
                category_id: string | null;
                name: string;
                /** Format: int64 */
                amount: number;
                percent: number;
            }[];
            previous: {
                /** Format: int64 */
                total_income: number;
                /** Format: int64 */
                total_expense: number;
                expense_change_percent: number | null;
            };
            daily: {
                /** Format: date */
                date: string;
                /** Format: int64 */
                income: number;
                /** Format: int64 */
                expense: number;
            }[];
        };
        Budget: {
            /** Format: uuid */
            category_id: string;
            month: string;
            limit_amount: components["schemas"]["Money"];
            spent: components["schemas"]["Money"];
            /**
             * @description safe < 80%, near ≥ 80%, over ≥ 100%
             * @enum {string}
             */
            status: "safe" | "near" | "over";
        };
    };
    responses: {
        /** @description Permintaan tidak valid */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Belum masuk atau sesi kedaluwarsa */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Tidak diizinkan */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Tidak ditemukan */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Konflik (mis. email sudah terdaftar) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Validasi gagal */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Terlalu banyak permintaan */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Database belum bisa dihubungi */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Id: string;
        /** @description Bulan dalam format YYYY-MM (default bulan ini, zona Asia/Jakarta) */
        Month: string;
        /** @description Bulan dalam format YYYY-MM */
        MonthRequired: string;
        /** @description Lapisan CSRF tambahan untuk permintaan yang mengubah data */
        XRequestedWith: "fundly";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server dan database sehat */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header: {
                /** @description Lapisan CSRF tambahan untuk permintaan yang mengubah data */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Akun dibuat dan sesi dimulai */
            201: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header: {
                /** @description Lapisan CSRF tambahan untuk permintaan yang mengubah data */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Sesi dimulai */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                /** @description Lapisan CSRF tambahan untuk permintaan yang mengubah data */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesi dihapus */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    googleStart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect ke halaman persetujuan Google */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    googleCallback: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesi dimulai, redirect ke aplikasi */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profil pengguna */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header: {
                /** @description Lapisan CSRF tambahan untuk permintaan yang mengubah data */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Konfirmasi eksplisit
                     * @constant
                     */
                    confirm: "HAPUS";
                };
            };
        };
        responses: {
            /** @description Akun dan semua data dihapus */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Unprocessable"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header: {
                /** @description Lapisan CSRF tambahan untuk permintaan yang mengubah data */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Profil diperbarui */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Unprocessable"];
        };
    };
    listWallets: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar dompet */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Wallet"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createWallet: {
        parameters: {
            query?: never;
            header: {
                /** @description Lapisan CSRF tambahan untuk permintaan yang mengubah data */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WalletCreate"];
            };
        };
        responses: {
            /** @description Dompet dibuat */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wallet"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Unprocessable"];
        };
    };
    updateWallet: {
        parameters: {
            query?: never;
            header: {
                /** @description Lapisan CSRF tambahan untuk permintaan yang mengubah data */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WalletUpdate"];
            };
        };
        responses: {
            /** @description Dompet diperbarui */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wallet"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
        };
    };
    listCategories: {
        parameters: {
            query?: {
                kind?: components["schemas"]["Kind"];
                include_hidden?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar kategori */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Category"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header: {
                /** @description Lapisan CSRF tambahan untuk permintaan yang mengubah data */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Kategori dibuat */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Unprocessable"];
        };
    };
    updateCategory: {
        parameters: {
            query?: never;
            header: {
                /** @description Lapisan CSRF tambahan untuk permintaan yang mengubah data */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdate"];
            };
        };
        responses: {
            /** @description Kategori diperbarui */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
        };
    };
    suggestCategory: {
        parameters: {
            query?: never;
            header: {
                /** @description Lapisan CSRF tambahan untuk permintaan yang mengubah data */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    merchant?: string | null;
                    note?: string | null;
                    kind?: components["schemas"]["Kind"];
                };
            };
        };
        responses: {
            /** @description Saran (category_id null bila tidak ada kecocokan) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        category_id: string | null;
                        confidence: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                /** @description Bulan dalam format YYYY-MM (default bulan ini, zona Asia/Jakarta) */
                month?: components["parameters"]["Month"];
                wallet_id?: string;
                category_id?: string;
                kind?: components["schemas"]["Kind"];
                q?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Satu halaman transaksi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Transaction"][];
                        next_cursor: string | null;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header: {
                /** @description Lapisan CSRF tambahan untuk permintaan yang mengubah data */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Transaksi dengan client_id yang sama sudah ada (dikembalikan apa adanya) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            /** @description Transaksi dibuat */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["Unprocessable"];
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaksi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteTransaction: {
        parameters: {
            query?: never;
            header: {
                /** @description Lapisan CSRF tambahan untuk permintaan yang mengubah data */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaksi dihapus */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTransaction: {
        parameters: {
            query?: never;
            header: {
                /** @description Lapisan CSRF tambahan untuk permintaan yang mengubah data */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionUpdate"];
            };
        };
        responses: {
            /** @description Transaksi diperbarui */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
        };
    };
    restoreTransaction: {
        parameters: {
            query?: never;
            header: {
                /** @description Lapisan CSRF tambahan untuk permintaan yang mengubah data */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaksi dipulihkan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getMonthlyReport: {
        parameters: {
            query: {
                /** @description Bulan dalam format YYYY-MM */
                month: components["parameters"]["MonthRequired"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ringkasan bulan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyReport"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listBudgets: {
        parameters: {
            query: {
                /** @description Bulan dalam format YYYY-MM */
                month: components["parameters"]["MonthRequired"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar anggaran */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Budget"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    putBudget: {
        parameters: {
            query: {
                /** @description Bulan dalam format YYYY-MM */
                month: components["parameters"]["MonthRequired"];
            };
            header: {
                /** @description Lapisan CSRF tambahan untuk permintaan yang mengubah data */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    limit_amount: components["schemas"]["Money"];
                };
            };
        };
        responses: {
            /** @description Anggaran disimpan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Budget"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
        };
    };
    deleteBudget: {
        parameters: {
            query: {
                /** @description Bulan dalam format YYYY-MM */
                month: components["parameters"]["MonthRequired"];
            };
            header: {
                /** @description Lapisan CSRF tambahan untuk permintaan yang mengubah data */
                "X-Requested-With": components["parameters"]["XRequestedWith"];
            };
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Anggaran dihapus */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    exportTransactionsCsv: {
        parameters: {
            query?: {
                /** @description Bulan dalam format YYYY-MM (default bulan ini, zona Asia/Jakarta) */
                month?: components["parameters"]["Month"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File CSV */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
